#!/usr/bin/env python3
"""Merge localized healthbar aliases into data/nightlord_tables.json."""

from __future__ import annotations

import json
from pathlib import Path

# Official / wiki Nightreign healthbar titles plus reused ER/DS names.
# JP: Game8. KO: namuwiki Nightreign boss list. ZH: Bilibili / GamerSky.
# EU: official Elden Ring / Dark Souls strings where the enemy is reused;
# Nightreign-only titles follow the JP 宿将 / 君主 pattern.
EXTRA: dict[str, list[str]] = {
    "battlefield": [
        "戦場の宿将",
        "전장의 노장",
        "战场老将",
        "戰場老將",
        "Commandant de champ de bataille",
        "Schlachtfeldkommandant",
        "Comandante del campo de batalla",
        "Comandante del campo di battaglia",
        "Comandante do campo de batalha",
        "Dowódca pola bitwy",
        "Командир поля боя",
    ],
    "bbh": [
        "鈴玉狩り",
        "鈴玉の狩人",
        "방울 사냥꾼",
        "방울구슬 사냥꾼",
        "铃珠猎人",
        "鈴珠獵人",
        "Chasseur de pommeaux",
        "Glockenkugeljäger",
        "Cazador de sonajas",
        "Cacciatore di batacchi",
        "Caçador de guizos",
        "Łowca kul dzwonkowych",
        "Охотник за колокольными сферами",
    ],
    "centipede": [
        "百足のデーモン",
        "ムカデのデーモン",
        "지네 데몬",
        "百足恶魔",
        "百足惡魔",
        "Démon Mille-pattes",
        "Tausendfüßler-Dämon",
        "Demonio ciempiés",
        "Demone centipede",
        "Demônio centopeia",
        "Demon stonoga",
        "Демон-сороконожка",
    ],
    "demi": [
        "亜人の女王",
        "亜人の剣聖",
        "亜人の女王＆亜人の剣聖",
        "아인 여왕",
        "아인 검성",
        "아인 여왕 & 아인 검성",
        "亚人女王",
        "亚人剑圣",
        "亞人女王",
        "亞人劍聖",
        "Reine demi-humaine",
        "Maître d'épée demi-humain",
        "Halb mensliche Königin",
        "Reina semihumana",
        "Regina semiumana",
        "Rainha semi-humana",
        "Królowa półludzi",
        "Королева полулюдей",
    ],
    "gaping": [
        "貪食ドラゴン",
        "탐식의 드래곤",
        "贪食魔龙",
        "貪食魔龍",
        "Dragon Béant",
        "Gähnender Drache",
        "Dragón Glotón",
        "Drago Famelico",
        "Dragão Boquiaberto",
        "Ziejący Smok",
        "Разверстый дракон",
    ],
    "grafted": [
        "接ぎ木の君主",
        "접목의 군주",
        "接肢君王",
        '"接肢"君王',
        "接肢君主",
        "Monarque greffé",
        "Gepfropfter Monarch",
        "Monarca injertado",
        "Monarca innestato",
        "Monarca enxertado",
        "Szczepiony monarcha",
        "Привитый монарх",
    ],
    "cavalry": [
        "夜の騎兵",
        "밤의 기병",
        "黑夜骑兵",
        "黑夜騎兵",
        "Cavalerie nocturne",
        "Nachtreiter",
        "Caballería nocturna",
        "Cavalleria notturna",
        "Cavalaria noturna",
        "Nocna kawaleria",
        "Ночная кавалерия",
    ],
    "revenant": [
        "王族の幽鬼",
        "왕족의 망령",
        "王室幽魂",
        "Revenant royal",
        "Königlicher Wiedergänger",
        "Aparecido real",
        "Redivivo reale",
        "Revenante real",
        "Królewski zjawa",
        "Королевский мертвец",
    ],
    "smelter": [
        "溶鉄デーモン",
        "溶鉄のデーモン",
        "용철 데몬",
        "熔铁恶魔",
        "熔鐵惡魔",
        "Démon de la Fournaise",
        "Schmelz-Dämon",
        "Demonio de la fundición",
        "Demone della Fornace",
        "Demônio da fundição",
        "Demon Piecowy",
        "Демон Плавильни",
    ],
    "freja": [
        "公のフレイディア",
        "公爵の愛馬フレイヤ",
        "공작의 프레이자",
        "公爵的弗雷迪亚",
        "公爵的夫雷迪亚",
        "公爵的弗雷迪亞",
        "Freja, chère au duc",
        "Des Herzogs liebe Freja",
        "La querida Freja del duque",
        "La cara Freja del duca",
        "A querida Freja do duque",
        "Ukochana Freja księcia",
        "Любимица герцога Фрейя",
    ],
    "tibia": [
        "ティビアの呼び舟",
        "死に生きる者たち",
        "티비아의 배",
        "죽음에 사는 자들",
        "提比亚的唤声船",
        "提比亞的喚聲船",
        "Marin tibia",
        "Ceux qui vivent dans la Mort",
        "Tibia-Schiffer",
        "Marinero tibia",
        "Nocchiero tibia",
        "Marinheiro tibia",
        "Żeglarz Tibii",
        "Мореход Тибии",
        "Живущие в смерти",
    ],
    "tree": [
        "爛れた樹霊",
        "문드러진 나무령",
        "腐烂树灵",
        "腐爛樹靈",
        "Esprit d'arbre ulcéré",
        "Vereitertes Baumwesen",
        "Espíritu de árbol ulcerado",
        "Spirito d'albero ulcerato",
        "Espírito de árvore ulcerado",
        "Owrzodzony duch drzewa",
        "Изъязвленный древесный дух",
    ],
    "gargoyle": [
        "英雄のガーゴイル",
        "영웅의 가고일",
        "英雄石像鬼",
        "Gargouille vaillante",
        "Tapfere Gargoyle",
        "Gárgola valerosa",
        "Gargoyle valoroso",
        "Gárgula valorosa",
        "Dzielna gargulec",
        "Доблестный горгулья",
    ],
    "wormface": [
        "ミミズ顔",
        "지렁이 얼굴",
        "蚯蚓脸",
        "蚯蚓臉",
        "Visage-ver",
        "Wurmgesicht",
        "Caragusano",
        "Volto verminoso",
        "Cara-de-minhoca",
        "Twarz robaka",
        "Червемордый",
    ],
    "deathknight": [
        "死の騎士",
        "죽음의 기사",
        "死骑士",
        "死騎士",
        "死骑士们",
        "Chevalier de la Mort",
        "Todesritter",
        "Caballero de la Muerte",
        "Cavaliere della Morte",
        "Cavaleiro da Morte",
        "Rycerz Śmierci",
        "Рыцарь Смерти",
    ],
    "demons": [
        "苦悶のデーモン",
        "下界のデーモン",
        "고통의 데몬",
        "하계의 데몬",
        "负伤恶魔",
        "洞底恶魔",
        "負傷惡魔",
        "洞底惡魔",
        "Démon en souffrance",
        "Démon d'en bas",
        "Dämon der Qual",
        "Dämon aus der Tiefe",
        "Demonio atribulado",
        "Demonio de las profundidades",
        "Demone sofferente",
        "Demone dal sottosuolo",
        "Demônio sofrido",
        "Demônio das profundezas",
        "Demon Cierpienia",
        "Demon z Otchłani",
        "Демон страдания",
        "Демон из глубин",
    ],
    "warrior": [
        "神獣戦士",
        "呪剣士",
        "신수 전사",
        "저주검객",
        "神兽战士",
        "咒剑士",
        "神獸戰士",
        "呪劍士",
        "Guerrier de la bête divine",
        "Lame maudite",
        "Krieger der göttlichen Bestie",
        "Fluchklinge",
        "Guerrero de la bestia divina",
        "Hoja maldita",
        "Guerriero della belva divina",
        "Lama maledetta",
        "Guerreiro da fera divina",
        "Lâmina amaldiçoada",
        "Wojownik boskiej bestii",
        "Przeklęta klinga",
        "Воин божественного зверя",
        "Проклятый клинок",
    ],
    "bear": [
        "大赤熊",
        "대적웅",
        "大紅熊",
        "大红熊",
        "Grand ours rouge",
        "Großer Roter Bär",
        "Gran oso rojo",
        "Grande orso rosso",
        "Grande urso vermelho",
        "Wielki czerwony niedźwiedź",
        "Большой красный медведь",
    ],
    "ancient": [
        "古竜",
        "고룡",
        "古龙",
        "古龍",
        "Dragon ancien",
        "Uralter Drache",
        "Dragón ancestral",
        "Drago antico",
        "Dragão ancestral",
        "Starożytny smok",
        "Древний дракон",
    ],
    "crucible": [
        "坩堝の騎士",
        "黄金のカバ",
        "도가니의 기사",
        "황금 하마",
        "熔炉骑士",
        "黄金河马",
        "熔爐騎士",
        "黃金河馬",
        "Chevalier du Creuset",
        "Hippopotame doré",
        "Ritter des Tiegels",
        "Goldenes Flusspferd",
        "Caballero del Crisol",
        "Hipopótamo dorado",
        "Cavaliere del Crogiolo",
        "Ippopotamo dorato",
        "Cavaleiro do Crisol",
        "Hipopótamo dourado",
        "Rycerz Tygla",
        "Złoty hipopotam",
        "Рыцарь Горнила",
        "Золотой гиппопотам",
    ],
    "dancer": [
        "冷たい谷の踊り子",
        "踊り子",
        "차가운 골짜기의 무희",
        "冷冽谷的舞娘",
        "Danseuse de la Vallée boréale",
        "Tänzerin des borealen Tals",
        "Bailarina del Valle Boreal",
        "Danzatrice della Valle Boreale",
        "Dançarina do Vale Boreal",
        "Tancerka Borealnej Doliny",
        "Танцовщица Холодной долины",
    ],
    "deathrite": [
        "死儀礼の鳥",
        "죽음 의례의 새",
        "死亡仪式鸟",
        "死亡儀式鳥",
        "Oiseau du rite funéraire",
        "Todesritusvogel",
        "Ave del rito fúnebre",
        "Uccello del rito funebre",
        "Ave do rito fúnebre",
        "Ptak rytuału śmierci",
        "Птица обряда смерти",
    ],
    "draconic": [
        "竜のツリーガード",
        "용의 트리 가드",
        "龙装大树守卫",
        "龍裝大樹守衛",
        "Sentinelle draconique de l'Arbre",
        "Drakonische Baumwächterin",
        "Centinela dracónica del Árbol",
        "Sentinella draconica dell'Albero",
        "Sentinela dracônica da Árvore",
        "Smoczy Strażnik Drzewa",
        "Драконий страж Древа",
    ],
    "fallingstar": [
        "降る星の成獣",
        "降る星の獣",
        "내리는 별의 짐승 성체",
        "내리는 별의 짐승",
        "坠星成兽",
        "墜星成獸",
        "Bête d'étoile filante adulte",
        "Ausgewachsene Sternenfallbestie",
        "Bestia de estrella fugaz adulta",
        "Bestia della stella cadente adulta",
        "Fera da estrela cadente adulta",
        "Dorosła bestia spadającej gwiazdy",
        "Взрослый зверь падающей звезды",
    ],
    "fell": [
        "忌み鬼",
        "マルギット",
        "끔찍한 흉조",
        "악兆요괴",
        "恶兆妖鬼",
        "惡兆妖鬼",
        "Augure réprouvé",
        "Margit l'Augure réprouvé",
        "Unheilvolles Omen",
        "Margit das Unheilvolle Omen",
        "Augurio vil",
        "Presagio nefando",
        "Agouro Vil",
        "Nikczemna wróżba",
        "Гибельное знамение",
        "Маргит",
    ],
    "godskin": [
        "神肌の貴種",
        "神肌の使徒",
        "神肌の双子",
        "신의 살갗의 귀인",
        "신의 살갗의 사도",
        "神皮贵族",
        "神皮使徒",
        "神皮双人组",
        "神皮貴族",
        "神皮使徒",
        "Noble sanctéchaire",
        "Apôtre sanctéchaire",
        "Gotteshaut-Adliger",
        "Gotteshaut-Apostel",
        "Noble piel de dios",
        "Apóstol piel de dios",
        "Nobile pellidia",
        "Apostolo pellidia",
        "Nobre da pele divina",
        "Apóstolo da pele divina",
        "Szlachetny Boskiej Skóry",
        "Apostoł Boskiej Skóry",
        "Вельможа богошкурых",
        "Апостол богошкурых",
    ],
    "wyrm": [
        "大土竜",
        "대토룡",
        "大土龙",
        "大土龍",
        "Grand wyrm",
        "Großer Wyrm",
        "Gran vermis",
        "Grande wyrm",
        "Wielki smok ziemny",
        "Великий змий",
    ],
    "nameless": [
        "無名の王",
        "이름 없는 왕",
        "无名王者",
        "無名王者",
        "Roi sans nom",
        "Namenloser König",
        "Rey innominado",
        "Re senza nome",
        "Rei sem nome",
        "Bezimienny Król",
        "Безымянный король",
    ],
    "nox": [
        "ノクスの竜人兵",
        "녹스의 용인병",
        "诺克斯龙人士兵",
        "諾克斯龍人士兵",
        "Soldat draconique de Nox",
        "Nox-Drachenmensch",
        "Soldado draconiano de Nox",
        "Soldato draconico di Nox",
        "Soldado dracônico de Nox",
        "Smoczy żołnierz Nox",
        "Драконий солдат Нокса",
    ],
    "outland": [
        "僻地の宿将",
        "벽지의 노장",
        "外域老将",
        "外域老將",
        "Commandant des contrées lointaines",
        "Kommandant der Einöde",
        "Comandante de las tierras remotas",
        "Comandante delle terre remote",
        "Comandante das terras longínquas",
        "Dowódca rubieży",
        "Командир окраин",
    ],
    "treesent": [
        "ツリーガード",
        "트리 가드",
        "大树守卫",
        "大樹守衛",
        "Sentinelle de l'Arbre",
        "Baumwächterin",
        "Centinela del Árbol",
        "Sentinella dell'Albero",
        "Sentinela da Árvore",
        "Strażnik Drzewa",
        "Страж Древа",
        "王都の騎兵",
        "도읍 기병",
        "王城骑兵",
        "王城騎兵",
    ],
    "artorias": [
        "騎士アルトリウス",
        "기사 아르토리우스",
        "骑士亚尔特留斯",
        "騎士亞爾特留斯",
        "Chevalier Artorias",
        "Ritter Artorias",
        "Caballero Artorias",
        "Cavaliere Artorias",
        "Cavaleiro Artorias",
        "Rycerz Artorias",
        "Рыцарь Арториас",
    ],
    "lion": [
        "神獣獅子舞",
        "신수 사자춤",
        "神兽舞狮",
        "神獸舞獅",
        "Lion dansant de la bête divine",
        "Tanzender Löwe der göttlichen Bestie",
        "León danzante de la bestia divina",
        "Leone danzante della belva divina",
        "Leão dançante da fera divina",
        "Tańczący lew boskiej bestii",
        "Танцующий лев божественного зверя",
    ],
    "mohg": [
        "血の君主モーグ",
        "피의 군주 모그",
        "鲜血君王",
        "鮮血君王",
        "蒙格",
        "Mohg, Seigneur du Sang",
        "Mohg, Herr des Blutes",
        "Mohg, Señor de la Sangre",
        "Mohg, Signore del Sangue",
        "Mohg, Senhor do Sangue",
        "Mohg, Władca Krwi",
        "Мог, Повелитель Крови",
    ],
    "demonprince": [
        "デーモンプリンス",
        "데몬 프린스",
        "恶魔王子",
        "惡魔王子",
        "Prince démon",
        "Dämonenprinz",
        "Príncipe demonio",
        "Principe demone",
        "Príncipe demônio",
        "Książę Demonów",
        "Принц демонов",
    ],
}


def main() -> None:
    path = Path(__file__).resolve().parents[1] / "data" / "nightlord_tables.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    for section in ("night1", "night2"):
        for key, entry in data[section].items():
            extra = EXTRA.get(key, [])
            seen: set[str] = set()
            merged: list[str] = []
            for alias in list(entry["aliases"]) + extra:
                alias = alias.strip()
                if not alias or alias in seen:
                    continue
                seen.add(alias)
                merged.append(alias)
            entry["aliases"] = merged
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"updated {path}")


if __name__ == "__main__":
    main()
